#!/usr/bin/env python3
"""Build and select an immutable Helm artifact from one committed Git tree.

This file is deliberately standalone: deployment must still work when the
mutable ``helm`` package in the source checkout does not import.
"""
import argparse
import ast
import fcntl
import hashlib
import io
import json
import os
import posixpath
import shutil
import stat
import struct
import subprocess
import sys
import tarfile
import tempfile


SCHEMA = 1
# GIT SELECTION ENV OVERRIDES `-C`, WHICH MAKES EVERY `git -C <path>` HERE A
# REQUEST RATHER THAN AN INSTRUCTION. Measured: with GIT_DIR and GIT_WORK_TREE
# pointing at repository B, `git -C A rev-parse --show-toplevel` answers B. So
# `--project A` would resolve its artifact root inside B and ask B whether the
# path is ignored — the project-local runtime would bind the WRONG repository,
# defeating the one invariant the mode exists to hold, with no flag involved.
# This mirrors `dispatches._GIT_SELECTION_ENV` deliberately rather than
# importing it: this file must keep working when the mutable package does not
# import, so the list is duplicated and must be kept in step with that one.
_GIT_SELECTION_ENV = ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE",
                      "GIT_COMMON_DIR", "GIT_OBJECT_DIRECTORY",
                      "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_NAMESPACE",
                      "GIT_CEILING_DIRECTORIES")


def _git_env():
    """The environment with Git's repository-SELECTION variables removed."""
    return {k: v for k, v in os.environ.items()
            if k not in _GIT_SELECTION_ENV}


MANIFEST = "artifact-manifest.json"
REQUIRED_FILES = (
    "bin/helm",
    "bin/helm-hook",
    "helm/__init__.py",
    "helm/cli.py",
    "README.md",
)
REQUIRED_TREES = ("docs/", "tests/")
# EVERY SHIPPED ENTRY POINT, NOT THE ONE SOMEONE REMEMBERED TO NAME. Both mode
# checks used to spell `bin/helm` inline, so the second entry point the tree
# grew — `bin/helm-hook`, which every generated hook command in every settings
# file now execs — was in no registry at all: an artifact that shipped it
# absent or mode 644 passed every deploy gate, and the whole fleet would then
# fail OPEN on every hook with nothing in helm's voice saying why (the wrapper
# cannot announce its own absence; the shell exits 127 first). A list both
# checks iterate makes the next entry point a one-line addition instead of a
# silent omission.
EXECUTABLE_FILES = ("bin/helm", "bin/helm-hook")

LAUNCHER = b'''#!/usr/bin/env python3
"""Stable Helm artifact launcher. Generated by scripts/deploy.py."""
import os
import stat
import sys


def fail(message):
    print("helm artifact launcher: " + message, file=sys.stderr)
    return 126


def main():
    launcher = os.path.realpath(__file__)
    root = os.path.dirname(os.path.dirname(launcher))
    current = os.path.join(root, "current")
    releases = os.path.join(root, "releases")

    try:
        target = os.readlink(current)  # Resolve the mutable pointer exactly once.
    except OSError as exc:
        return fail("cannot read current symlink: %s" % exc)
    parts = target.split(os.sep)
    if (len(parts) != 2 or parts[0] != "releases"
            or len(parts[1]) not in (40, 64)
            or any(c not in "0123456789abcdef" for c in parts[1])):
        return fail("refusing current target outside releases/<commit>: %s" % target)

    try:
        releases_mode = os.lstat(releases).st_mode
    except OSError as exc:
        return fail("cannot inspect releases directory: %s" % exc)
    if not stat.S_ISDIR(releases_mode):
        return fail("releases is not a real directory: %s" % releases)

    release = os.path.join(releases, parts[1])
    try:
        release_mode = os.lstat(release).st_mode
    except OSError as exc:
        return fail("cannot inspect selected release: %s" % exc)
    if not stat.S_ISDIR(release_mode):
        return fail("selected release is not a real directory: %s" % release)

    entry = os.path.join(release, "bin", "helm")
    if os.path.realpath(entry) != entry:
        return fail("refusing non-concrete release entrypoint: %s" % entry)
    try:
        mode = os.lstat(entry).st_mode
    except OSError as exc:
        return fail("cannot inspect release entrypoint: %s" % exc)
    if not stat.S_ISREG(mode):
        return fail("release entrypoint is not a regular file: %s" % entry)

    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env.pop("PYTHONPATH", None)
    try:
        os.execve(entry, [entry] + sys.argv[1:], env)
    except OSError as exc:
        return fail("cannot exec release entrypoint: %s" % exc)


if __name__ == "__main__":
    sys.exit(main())
'''


class DeployError(RuntimeError):
    pass


def _default_root():
    base = os.environ.get("XDG_DATA_HOME")
    if not base or not os.path.isabs(base):
        base = os.path.join(os.path.expanduser("~"), ".local", "share")
    return os.path.join(base, "helm", "artifacts")


def _require_ignored(repo, path):
    """Refuse unless ``path`` is ignored by ``repo``, BEFORE anything is written.

    THIS IS A PRECONDITION, NOT A CLEANUP STEP, and the distinction is the
    whole value. gitignore does not affect repository discovery — a package
    under an ignored path still resolves its identity perfectly well — so this
    check is not what makes a project-local runtime work. It is what stops a
    deploy from depositing an artifact tree into somebody's working copy,
    where it sits in `git status` as untracked cruft one `git add -A` away
    from being committed. A refused deploy must leave the project byte-for-byte
    as it was found, so this runs before the first mkdir rather than after.

    AN UNREADABLE ANSWER REFUSES; IT DOES NOT WAVE THROUGH. `check-ignore`
    exits 0 for ignored, 1 for not-ignored, and anything else means the
    question could not be answered — a missing repo, a broken index, a git
    that failed to run. Treating that third case as "probably fine" would make
    the guard refuse nothing exactly when it cannot see, which is the failure
    `dispatches.home_repo_id` was rewritten to close on the write door. Same
    law here.
    """
    proc = subprocess.run(
        ["git", "-C", repo, "check-ignore", "-q", path],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=_git_env())
    if proc.returncode == 0:
        return
    if proc.returncode == 1:
        raise DeployError(
            "refusing to deploy into %s because %s does not ignore it.\n"
            "A project-local runtime lands thousands of files inside the "
            "project; unignored they become untracked cruft that a single "
            "`git add -A` commits.\n"
            "Add a line matching .cache/ to that repository's .gitignore and "
            "run this again — nothing has been written." % (path, repo))
    detail = proc.stderr.decode("utf-8", "replace").strip()
    raise DeployError(
        "cannot determine whether %s is ignored by %s, so the deploy is "
        "refused rather than attempted unchecked: %s"
        % (path, repo, detail or "git check-ignore failed"))


def _project_artifact_root(project):
    """``<toplevel>/.cache/helm-artifacts`` for ``project``, or refuse.

    A HELM DEPLOYED HERE *IS* THAT PROJECT, and that is the entire point of
    the mode. ``dispatches.home_repo_id`` derives repository identity from the
    running package's OWN location rather than from cwd or any rebuildable
    cache, so an artifact under ``<project>/.cache`` resolves its home to that
    project's gitdir: a dispatch filed from it succeeds locally and a ref from
    a sibling repository is refused by ``_foreign_repo_refusal`` — the same
    law, unweakened. There is deliberately NO flag to point this elsewhere,
    because a project-local runtime that could be aimed at a sibling would
    reintroduce precisely the cross-repo mint it exists to avoid.

    THE ROOT IS PER WORKING TREE, resolved through ``--show-toplevel`` rather
    than used as given, so ``--project A`` and ``--project A/sub/dir`` name one
    runtime instead of two identical ones. Identity is a property of the
    repository, so the artifact root that carries it should be too.
    """
    project = os.path.realpath(os.path.abspath(os.path.expanduser(project)))
    if not os.path.isdir(project):
        raise DeployError("--project %s is not a directory" % project)
    try:
        top = os.path.realpath(_git(project, ["rev-parse", "--show-toplevel"]))
    except DeployError as exc:
        raise DeployError(
            "--project %s is not inside a Git working tree, so there is no "
            "repository identity for a project-local runtime to bind (%s)"
            % (project, exc))
    root = os.path.join(top, ".cache", "helm-artifacts")
    _require_ignored(top, root)
    return root


def _git(repo, args, binary=False):
    proc = subprocess.run(
        ["git", "-C", repo] + list(args),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=_git_env(),
    )
    if proc.returncode:
        detail = proc.stderr.decode("utf-8", "replace").strip()
        raise DeployError("git %s failed: %s" % (" ".join(args), detail))
    if binary:
        return proc.stdout
    return proc.stdout.decode("utf-8", "strict").strip()


def _reject_tracked_dirt(repo):
    checks = (
        ("unstaged", ["diff", "--quiet", "--no-ext-diff",
                      "--ignore-submodules=none", "--"]),
        ("staged", ["diff", "--cached", "--quiet", "--no-ext-diff",
                    "--ignore-submodules=none", "--"]),
    )
    for label, args in checks:
        proc = subprocess.run(
            ["git", "-C", repo] + args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=_git_env(),
        )
        if proc.returncode == 1:
            raise DeployError("refusing %s tracked source changes" % label)
        if proc.returncode:
            detail = proc.stderr.decode("utf-8", "replace").strip()
            raise DeployError("cannot inspect %s tracked changes: %s" %
                              (label, detail))


def _source(repo, revision):
    if revision.startswith("-"):
        raise DeployError("revision must not start with '-'")
    top = _git(repo, ["rev-parse", "--show-toplevel"])
    if os.path.realpath(top) != os.path.realpath(repo):
        raise DeployError("deployer must live under the source repository root")
    commit = _git(repo, ["rev-parse", "--verify", revision + "^{commit}"])
    if (len(commit) not in (40, 64)
            or any(c not in "0123456789abcdef" for c in commit)):
        raise DeployError("git did not resolve a full commit: %r" % commit)
    tree = _git(repo, ["rev-parse", "--verify", commit + "^{tree}"])
    _reject_tracked_dirt(repo)
    return commit, tree


def _safe_archive_name(raw, is_dir):
    name = raw[:-1] if is_dir and raw.endswith("/") else raw
    if not name or name.startswith("/") or "\x00" in name:
        raise DeployError("unsafe archive path: %r" % raw)
    parts = name.split("/")
    if any(part in ("", ".", "..") for part in parts):
        raise DeployError("unsafe archive path: %r" % raw)
    return name


def _safe_link(name, target):
    if not target or target.startswith("/") or "\x00" in target:
        raise DeployError("unsafe archive symlink %s -> %r" % (name, target))
    resolved = posixpath.normpath(
        posixpath.join(posixpath.dirname(name), target))
    if resolved == ".." or resolved.startswith("../"):
        raise DeployError("archive symlink escapes artifact: %s -> %s" %
                          (name, target))


def _read_archive(repo, commit):
    raw = _git(repo, ["archive", "--format=tar", commit], binary=True)
    entries = {}
    try:
        with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as archive:
            for member in archive:
                is_dir = member.isdir()
                name = _safe_archive_name(member.name, is_dir)
                if name in entries:
                    raise DeployError("duplicate archive path: %s" % name)
                if is_dir:
                    entries[name] = ("dir", 0o755, None)
                    continue
                if member.isfile():
                    stream = archive.extractfile(member)
                    if stream is None:
                        raise DeployError("archive file has no payload: %s" % name)
                    mode = 0o755 if member.mode & 0o111 else 0o644
                    entries[name] = ("file", mode, stream.read())
                    continue
                if member.issym():
                    _safe_link(name, member.linkname)
                    entries[name] = ("link", 0o777, member.linkname)
                    continue
                raise DeployError("unsupported archive member: %s" % name)
    except tarfile.TarError as exc:
        raise DeployError("cannot read git archive: %s" % exc)
    if MANIFEST in entries:
        raise DeployError("tracked tree owns reserved path %s" % MANIFEST)
    return entries


def _required_entries(entries):
    for name in REQUIRED_FILES:
        entry = entries.get(name)
        if entry is None or entry[0] != "file":
            raise DeployError("archive is missing required regular file %s" % name)
    for prefix in REQUIRED_TREES:
        if not any(name.startswith(prefix) and entry[0] == "file"
                   for name, entry in entries.items()):
            raise DeployError("archive has no regular files under %s" % prefix)
    for name in EXECUTABLE_FILES:
        if not entries[name][1] & 0o111:
            raise DeployError("archive entry %s is not executable" % name)


def _package_version(data):
    try:
        tree = ast.parse(data.decode("utf-8"), filename="helm/__init__.py")
    except (SyntaxError, UnicodeDecodeError) as exc:
        raise DeployError("cannot parse package version: %s" % exc)
    found = []
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if isinstance(target, ast.Name) and target.id == "__version__":
            try:
                value = ast.literal_eval(node.value)
            except (ValueError, TypeError, SyntaxError):
                continue
            if isinstance(value, str):
                found.append(value)
    if len(found) != 1 or not found[0]:
        raise DeployError("helm/__init__.py must define one string __version__")
    return found[0]


def _feed(digest, value):
    digest.update(struct.pack(">Q", len(value)))
    digest.update(value)


def _content_digest(nodes):
    digest = hashlib.sha256()
    digest.update(b"helm-artifact-content-v1\0")
    for name, kind, mode, value in sorted(
            nodes, key=lambda row: os.fsencode(row[0])):
        digest.update(kind.encode("ascii"))
        _feed(digest, os.fsencode(name))
        digest.update(struct.pack(">I", mode & 0o777))
        if kind == "file":
            _feed(digest, value)
        elif kind == "link":
            _feed(digest, os.fsencode(value))
    return "sha256:" + digest.hexdigest()


def _archive_digest(entries):
    nodes = [(".", "dir", 0o555, None)]
    for name, (kind, mode, value) in entries.items():
        final_mode = mode if kind == "link" else mode & ~0o222
        nodes.append((name, kind, final_mode, value))
    return _content_digest(nodes)


def _artifact_paths(root):
    paths = []

    def visit(directory, prefix):
        try:
            with os.scandir(directory) as scan:
                children = sorted(scan,
                                  key=lambda child: os.fsencode(child.name))
        except OSError as exc:
            raise DeployError("cannot inspect artifact directory %s: %s" %
                              (directory, exc))
        for child in children:
            rel = child.name if not prefix else prefix + "/" + child.name
            try:
                info = child.stat(follow_symlinks=False)
            except OSError as exc:
                raise DeployError("cannot inspect artifact path %s: %s" %
                                  (rel, exc))
            if stat.S_ISDIR(info.st_mode):
                visit(child.path, rel)
            elif not (stat.S_ISREG(info.st_mode)
                      or stat.S_ISLNK(info.st_mode)):
                raise DeployError("unsupported artifact node: %s" % rel)
            paths.append((child.path, rel, info.st_mode, info.st_size))

    visit(root, "")
    info = os.lstat(root)
    paths.append((root, ".", info.st_mode, info.st_size))
    return paths


def _tree_digest(root, paths=None):
    if paths is None:
        paths = _artifact_paths(root)
    digest = hashlib.sha256()
    digest.update(b"helm-artifact-content-v1\0")
    for path, name, mode, size in sorted(
            paths, key=lambda row: os.fsencode(row[1])):
        if name == MANIFEST:
            continue
        if stat.S_ISDIR(mode):
            kind = "dir"
        elif stat.S_ISREG(mode):
            kind = "file"
        else:
            kind = "link"
        digest.update(kind.encode("ascii"))
        _feed(digest, os.fsencode(name))
        digest.update(struct.pack(">I", stat.S_IMODE(mode)))
        if kind == "file":
            digest.update(struct.pack(">Q", size))
            seen = 0
            try:
                with open(path, "rb") as handle:
                    while True:
                        chunk = handle.read(1024 * 1024)
                        if not chunk:
                            break
                        digest.update(chunk)
                        seen += len(chunk)
            except OSError as exc:
                raise DeployError("cannot read artifact file %s: %s" %
                                  (name, exc))
            if seen != size:
                raise DeployError("artifact file changed while hashing: %s" % name)
        elif kind == "link":
            try:
                target = os.readlink(path)
            except OSError as exc:
                raise DeployError("cannot read artifact symlink %s: %s" %
                                  (name, exc))
            _safe_link(name, target)
            _feed(digest, os.fsencode(target))
    return "sha256:" + digest.hexdigest()


def _ensure_directory(path):
    missing = []
    probe = path
    while not os.path.lexists(probe):
        missing.append(probe)
        parent = os.path.dirname(probe)
        if parent == probe:
            break
        probe = parent
    if os.path.lexists(probe):
        mode = os.lstat(probe).st_mode
        if not stat.S_ISDIR(mode):
            raise DeployError("artifact path is not a real directory: %s" % probe)
    for directory in reversed(missing):
        os.mkdir(directory, 0o755)
        _fsync_directory(os.path.dirname(directory))
    mode = os.lstat(path).st_mode
    if not stat.S_ISDIR(mode):
        raise DeployError("artifact path is not a real directory: %s" % path)


def _fsync_directory(path):
    flags = os.O_RDONLY
    if hasattr(os, "O_DIRECTORY"):
        flags |= os.O_DIRECTORY
    descriptor = os.open(path, flags)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _material_directory(root, parts, known):
    current = root
    for part in parts:
        current = os.path.join(current, part)
        if current in known:
            continue
        if os.path.lexists(current):
            mode = os.lstat(current).st_mode
            if not stat.S_ISDIR(mode):
                raise DeployError("archive path crosses non-directory: %s" % current)
        else:
            os.mkdir(current, 0o755)
            os.chmod(current, 0o755)
        known.add(current)
    return current


def _write_exclusive(path, data, mode):
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(path, flags, mode)
    try:
        with os.fdopen(descriptor, "wb", closefd=False) as handle:
            handle.write(data)
            handle.flush()
        os.fchmod(descriptor, mode)
    finally:
        os.close(descriptor)


def _extract(entries, stage):
    known = {stage}
    directories = [name for name, value in entries.items()
                   if value[0] == "dir"]
    for name in sorted(directories, key=lambda value: (value.count("/"), value)):
        _material_directory(stage, name.split("/"), known)

    for name, (kind, mode, value) in sorted(entries.items()):
        if kind == "dir":
            continue
        parts = name.split("/")
        parent = _material_directory(stage, parts[:-1], known)
        path = os.path.join(parent, parts[-1])
        if os.path.lexists(path):
            raise DeployError("archive path collides during extraction: %s" % name)
        if kind == "link":
            os.symlink(value, path)
        else:
            _write_exclusive(path, value, mode)


def _regular_path(root, name):
    current = root
    parts = name.split("/")
    for part in parts[:-1]:
        current = os.path.join(current, part)
        try:
            mode = os.lstat(current).st_mode
        except OSError as exc:
            raise DeployError("missing required directory %s: %s" % (name, exc))
        if not stat.S_ISDIR(mode):
            raise DeployError("required path crosses non-directory: %s" % name)
    current = os.path.join(current, parts[-1])
    try:
        mode = os.lstat(current).st_mode
    except OSError as exc:
        raise DeployError("missing required file %s: %s" % (name, exc))
    if not stat.S_ISREG(mode):
        raise DeployError("required path is not a regular file: %s" % name)
    return current, mode


def _verify_required(root, paths=None):
    for name in REQUIRED_FILES:
        _regular_path(root, name)
    if paths is None:
        paths = _artifact_paths(root)
    regular = {name for _, name, mode, _ in paths if stat.S_ISREG(mode)}
    for prefix in REQUIRED_TREES:
        if not any(name.startswith(prefix) for name in regular):
            raise DeployError("artifact has no regular files under %s" % prefix)
    for name in EXECUTABLE_FILES:
        path, mode = _regular_path(root, name)
        if not mode & 0o111:
            raise DeployError("staged %s is not executable: %s" % (name, path))


def _manifest(commit, tree, version, digest):
    return {
        "schema": SCHEMA,
        "commit": commit,
        "tree": tree,
        "package_version": version,
        "content_digest": digest,
    }


def _manifest_bytes(manifest):
    return (json.dumps(manifest, sort_keys=True, separators=(",", ":")) +
            "\n").encode("utf-8")


def _write_manifest(root, manifest):
    _write_exclusive(os.path.join(root, MANIFEST),
                     _manifest_bytes(manifest), 0o644)


def _smoke(root, version):
    entry, _ = _regular_path(root, "bin/helm")
    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env.pop("PYTHONPATH", None)
    try:
        proc = subprocess.run(
            [entry, "--version"],
            cwd=root,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise DeployError("staged bin/helm --version failed: %s" % exc)
    output = proc.stdout.decode("utf-8", "replace").strip()
    detail = proc.stderr.decode("utf-8", "replace").strip()
    expected = "helm " + version
    if proc.returncode or output != expected:
        raise DeployError(
            "staged bin/helm --version failed (exit %d, stdout %r, stderr %r)" %
            (proc.returncode, output, detail))


def _make_nonwritable(paths):
    sealed = []
    for path, name, mode, size in paths:
        final_mode = mode
        if not stat.S_ISLNK(mode):
            permissions = stat.S_IMODE(mode) & ~0o222
            os.chmod(path, permissions)
            final_mode = stat.S_IFMT(mode) | permissions
        sealed.append((path, name, final_mode, size))
    return sealed


def _assert_nonwritable(paths):
    for path, _, mode, _ in paths:
        if not stat.S_ISLNK(mode) and mode & 0o222:
            raise DeployError("artifact node is writable: %s" % path)


def _fsync_tree(paths):
    for path, _, mode, _ in paths:
        if stat.S_ISREG(mode):
            flags = os.O_RDONLY
            if hasattr(os, "O_NOFOLLOW"):
                flags |= os.O_NOFOLLOW
            descriptor = os.open(path, flags)
            try:
                os.fsync(descriptor)
            finally:
                os.close(descriptor)
    for path, _, mode, _ in paths:
        if stat.S_ISDIR(mode):
            _fsync_directory(path)


def _validate_release(release, expected):
    try:
        mode = os.lstat(release).st_mode
    except OSError as exc:
        raise DeployError("cannot inspect existing release: %s" % exc)
    if not stat.S_ISDIR(mode):
        raise DeployError("existing release is not a real directory: %s" % release)
    manifest_path, manifest_mode = _regular_path(release, MANIFEST)
    try:
        with open(manifest_path, "rb") as handle:
            actual_manifest = handle.read()
    except OSError as exc:
        raise DeployError("cannot read existing release manifest: %s" % exc)
    if (actual_manifest != _manifest_bytes(expected)
            or stat.S_IMODE(manifest_mode) != 0o444):
        raise DeployError("existing same-commit release manifest differs: %s" %
                          release)
    paths = _artifact_paths(release)
    _verify_required(release, paths)
    actual_digest = _tree_digest(release, paths)
    if actual_digest != expected["content_digest"]:
        raise DeployError("existing same-commit release digest differs: %s" %
                          release)
    _assert_nonwritable(paths)


def _cleanup_stage(stage):
    if not stage or not os.path.lexists(stage):
        return
    for path, _, mode, _ in _artifact_paths(stage):
        if stat.S_ISDIR(mode):
            os.chmod(path, 0o700)
    shutil.rmtree(stage)


def _launcher_action(root):
    directory = os.path.join(root, "bin")
    if os.path.lexists(directory):
        mode = os.lstat(directory).st_mode
        if not stat.S_ISDIR(mode):
            raise DeployError("launcher parent is not a real directory: %s" %
                              directory)
    path = os.path.join(directory, "helm")
    if not os.path.lexists(path):
        return "created"
    mode = os.lstat(path).st_mode
    if stat.S_ISDIR(mode):
        raise DeployError("launcher path is a directory: %s" % path)
    if stat.S_ISREG(mode):
        try:
            with open(path, "rb") as handle:
                data = handle.read()
        except OSError as exc:
            raise DeployError("cannot inspect launcher: %s" % exc)
        if data == LAUNCHER and stat.S_IMODE(mode) == 0o555:
            return "reused"
    return "created"


def _install_launcher(root):
    directory = os.path.join(root, "bin")
    _ensure_directory(directory)
    action = _launcher_action(root)
    if action == "reused":
        return action
    descriptor, temporary = tempfile.mkstemp(prefix=".helm-launcher-",
                                              dir=directory)
    try:
        with os.fdopen(descriptor, "wb", closefd=False) as handle:
            handle.write(LAUNCHER)
            handle.flush()
        os.fchmod(descriptor, 0o555)
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = None
        os.replace(temporary, os.path.join(directory, "helm"))
        _fsync_directory(directory)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if os.path.lexists(temporary):
            os.unlink(temporary)
    return action


def _current_action(root, target):
    current = os.path.join(root, "current")
    if not os.path.lexists(current):
        previous = None
    else:
        mode = os.lstat(current).st_mode
        if not stat.S_ISLNK(mode):
            raise DeployError("current exists and is not a symlink: %s" % current)
        previous = os.readlink(current)
    action = "reused" if previous == target else "selected"
    return action, previous


def _symlink_replace(directory, name, target):
    descriptor, temporary = tempfile.mkstemp(prefix=".%s-" % name,
                                              dir=directory)
    os.close(descriptor)
    os.unlink(temporary)
    try:
        os.symlink(target, temporary)
        os.replace(temporary, os.path.join(directory, name))
    finally:
        if os.path.lexists(temporary):
            os.unlink(temporary)


def _flip_current(root, target):
    action, previous = _current_action(root, target)
    if action == "reused":
        return action
    replaced = False
    try:
        _symlink_replace(root, "current", target)
        replaced = True
        _fsync_directory(root)
    except OSError as exc:
        if replaced:
            try:
                if previous is not None:
                    _symlink_replace(root, "current", previous)
                else:
                    os.unlink(os.path.join(root, "current"))
                _fsync_directory(root)
            except OSError as rollback:
                raise DeployError(
                    "current flip failed (%s) and rollback failed (%s)" %
                    (exc, rollback))
        raise DeployError("current flip failed: %s" % exc)
    return action


def _release_action(release, expected):
    if not os.path.lexists(release):
        return "created"
    _validate_release(release, expected)
    return "reused"


def _report(dry_run, release_action, launcher_action, current_action,
            commit, root):
    prefix = "helm deploy: dry-run" if dry_run else "helm deploy:"
    print("%s release=%s launcher=%s current=%s commit=%s root=%s" %
          (prefix, release_action, launcher_action, current_action,
           commit, root))


def deploy(repo, revision, root, dry_run):
    commit, tree = _source(repo, revision)
    entries = _read_archive(repo, commit)
    _required_entries(entries)
    version = _package_version(entries["helm/__init__.py"][2])
    digest = _archive_digest(entries)
    manifest = _manifest(commit, tree, version, digest)
    release = os.path.join(root, "releases", commit)
    target = os.path.join("releases", commit)

    if dry_run:
        release_action = _release_action(release, manifest)
        launcher_action = _launcher_action(root)
        current_action, _ = _current_action(root, target)
        _report(True, release_action, launcher_action, current_action,
                commit, root)
        return 0

    _ensure_directory(root)
    releases = os.path.join(root, "releases")
    _ensure_directory(releases)
    flags = os.O_RDONLY
    if hasattr(os, "O_DIRECTORY"):
        flags |= os.O_DIRECTORY
    lock = os.open(releases, flags)
    fcntl.flock(lock, fcntl.LOCK_EX)
    stage = None
    try:
        release_action = _release_action(release, manifest)
        if release_action == "reused":
            _smoke(release, version)
        else:
            stage = tempfile.mkdtemp(
                prefix=".staging-%s-" % commit[:12], dir=releases)
            _extract(entries, stage)
            _verify_required(stage)
            _write_manifest(stage, manifest)
            _smoke(stage, version)
            os.chmod(stage, 0o755)
            paths = _make_nonwritable(_artifact_paths(stage))
            staged_digest = _tree_digest(stage, paths)
            if staged_digest != digest:
                raise DeployError("staged artifact digest differs from archive")
            _assert_nonwritable(paths)
            _fsync_tree(paths)
            if os.path.lexists(release):
                _validate_release(release, manifest)
                release_action = "reused"
            else:
                os.replace(stage, release)
                stage = None
                _fsync_directory(releases)

        launcher_action = _install_launcher(root)
        current_action = _flip_current(root, target)
        _report(False, release_action, launcher_action, current_action,
                commit, root)
        return 0
    finally:
        _cleanup_stage(stage)
        fcntl.flock(lock, fcntl.LOCK_UN)
        os.close(lock)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="publish one immutable Helm tracked-tree artifact")
    parser.add_argument("revision", nargs="?", default="HEAD",
                        help="commit-ish to deploy (default: HEAD)")
    parser.add_argument("--root", default=None,
                        help="artifact root (default: %s)" % _default_root())
    parser.add_argument("--project", default=None,
                        help="deploy into <project>/.cache/helm-artifacts so "
                             "the runtime's repository identity is that "
                             "project; refuses unless the path is gitignored")
    parser.add_argument("--dry-run", action="store_true",
                        help="validate and report without writing")
    args = parser.parse_args(argv)

    if args.project is not None and args.root is not None:
        parser.error("--project and --root both name an artifact root; pass one")

    script = os.path.realpath(__file__)
    repo = os.path.dirname(os.path.dirname(script))
    try:
        # RESOLUTION IS INSIDE THE TRY because --project can REFUSE, and its
        # refusal is a deploy error the caller must see on stderr with rc 1 —
        # not an argparse usage error, and never a traceback.
        if args.project is not None:
            root = _project_artifact_root(args.project)
        else:
            root = os.path.realpath(os.path.abspath(os.path.expanduser(
                args.root or _default_root())))
        return deploy(repo, args.revision, root, args.dry_run)
    except (DeployError, OSError) as exc:
        print("helm deploy: error: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
