#!/usr/bin/env python3
import os
import shlex
import sys

from . import home

"""helm pi — the pi harness seam, and the eval's arm-pinning generator.

WHY THIS EXISTS BEFORE THE EXTENSION SLICE IT SEEMS TO BELONG TO. 0.3's §E-8
converged on shipping the EVIDENCE (the cc-codex vs pi-codex eval) and the thin
seat adapter, and DEFERRING the pi extension "until the eval proves pi earns
the surface." Correct instinct, wrong order — measured 2026-07-29:

  §E-5 pins the eval's two arms as "the codex model, same tier, same task
  suite" under two harnesses. On this host, `cc-codex` reaches codex through
  helm's CLIProxyAPI on the owner's SUBSCRIPTION OAuth, and pi has exactly one
  provider configured: openrouter. Running the arms as they stand would
  compare Claude-Code-over-subscription against pi-over-OpenRouter and
  attribute the whole difference to the harness. Different provider, different
  billing, different rate limits, possibly a different model build — the exact
  confound §E-5 exists to forbid.

The fix is to point pi at the SAME endpoint cc-codex already uses, so both arms
traverse the identical proxy, credentials and upstream and the ONLY difference
is the harness. pi's supported way to do that is an extension calling
`pi.registerProvider(...)` — so a minimal extension is a PREREQUISITE of the
eval, not a reward for it. This module generates only that: the provider
override. The reflex/chat bridge that §B.2 describes stays deferred.

ZERO TYPESCRIPT LIVES IN THIS REPO, which is §E-2's converged answer (option
iii): the shim is GENERATED on demand, so helm stays a stdlib-only Python
package and the .ts exists only where pi loads it from.

THE KEY IS NEVER WRITTEN DOWN. The generated provider reads one named process
environment variable at pi startup; the material stays in the seat's 0600 config
until `helm pi run` places it in the child environment. helm never prints it,
copies it into the generated file, or puts it in argv.
"""

# pi resolves an extension from its agent dir; this is the conventional home.
DEFAULT_DIR = os.path.join(os.path.expanduser("~"), ".pi", "agent", "extensions")

# The env var the generated provider reads its key from. Named for helm rather
# than for pi because helm's launch recipe is what will set it.
KEY_ENV = "HELM_PI_PROXY_KEY"


def provider_name(seat):
    return "helm-%s" % seat


def extension_source(seat, port, model, upstream=None, key_env=KEY_ENV,
                     host="127.0.0.1"):
    """The generated TypeScript. Deliberately tiny and dependency-free.

    It registers ONE provider pointing at a helm seat's local CLIProxyAPI, so a
    pi run and a Claude Code run reach the same upstream through the same proxy
    on the same credentials. `api: "openai-completions"` is what CLIProxyAPI
    speaks on its OpenAI-compatible route.
    """
    return '''// GENERATED BY `helm pi extension` — edit helm/pi.py, not this file.
//
// Points pi at helm's own CLIProxyAPI for seat "%(seat)s", so a pi run and a
// Claude Code run reach the SAME upstream, through the SAME proxy, on the SAME
// credentials. That is what makes a cc-vs-pi comparison a measurement of the
// HARNESS rather than of two different providers.
//
// The API key is read from the child PROCESS ENVIRONMENT, never a literal, so
// the material stays in the seat's 0600 proxy config and is not copied into
// this file. `helm pi run` sets %(key_env)s only for the pi child.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  pi.registerProvider("%(provider)s", {
    name: "helm seat %(seat)s (CLIProxyAPI)",
    baseUrl: "http://%(host)s:%(port)d/v1",
    apiKey: process.env["%(key_env)s"] || "",
    api: "openai-completions",
    models: [
      {
        id: "%(model)s",
        name: "%(model)s via helm/%(seat)s",
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: %(ctx)d,
        maxTokens: %(maxtok)d,
      },
    ],
  });
}
''' % {"seat": seat, "provider": provider_name(seat), "host": host,
       "port": port, "model": upstream or model, "key_env": key_env,
       "ctx": 400000, "maxtok": 64000}


def seat_port(seat):
    """(port, err) for a helm seat, read from the family table — NOT from the
    seat's config.yaml, which carries the proxy token. There is no reason to
    open a 0600 credential file to learn a port number."""
    from . import seat as seatmod
    family, err = seatmod._seat_family(seat)
    if err:
        return None, err
    fam = seatmod.FAMILIES.get(family) or {}
    port = fam.get("port")
    if not port:
        return None, "family %s declares no proxy port" % family
    # instances get their own port; the family table holds the base and
    # seat.py owns the offset, so ask it rather than recomputing the rule here
    getter = getattr(seatmod, "_instance_port", None)
    if callable(getter):
        try:
            return getter(family, seat) or port, None
        except Exception:
            pass
    return port, None


def write_extension(seat, out=None, model=None, apply=False):
    """-> (path, source, err). Writes only when apply is True."""
    from . import seat as seatmod
    port, err = seat_port(seat)
    if err:
        return None, None, err
    family, _ = seatmod._seat_family(seat)
    fam = seatmod.FAMILIES.get(family) or {}
    model = model or fam.get("model")
    if not model:
        return None, None, "family %s declares no model" % family
    src = extension_source(seat, port, model)
    path = out or os.path.join(DEFAULT_DIR, "helm-%s.ts" % seat)
    if not apply:
        return path, src, None
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(src)
    except OSError as e:
        return path, src, "could not write %s (%s)" % (path, e)
    return path, src, None


_USAGE = """usage: helm pi extension [--seat S] [--out PATH] [--model M] [--apply]
       helm pi run [SEAT] [--model helm-SEAT/MODEL] [PI_ARGS...]
       helm pi launch [--model M] [--session ID] [--session-dir DIR]
              [--print]
       helm pi resume --session ID [--session-dir DIR]
       helm pi resume --continue [--session-dir DIR]
       helm pi status

  extension  GENERATE a pi extension that points pi at a helm seat's own
             CLIProxyAPI, so a pi run and a Claude Code run reach the same
             upstream through the same proxy on the same credentials. Without
             it a cc-vs-pi comparison measures the PROVIDER, not the harness.
             Prints the shim by default; --apply writes it to pi's extension
             dir. The generated file reads %s from the child environment,
             never a literal; helm never prints the seat's proxy token.
  run        exec pi through SEAT's generated helm-SEAT provider. Defaults the
             model to that provider, refuses a conflicting provider, and puts
             the proxy key only in the child environment.
  launch     print the exact pi launch command (never runs it)
  resume     print the exact pi resume command (session id or --continue)
  status     is pi installed, where are its sessions, what does helm see.
""" % KEY_ENV


def cmd_pi(args):
    """pi — the pi harness seam: extension generator, install status."""
    args = list(args or [])
    verb = args[0] if args else ""
    if not verb or verb in ("-h", "--help", "help"):
        print(_USAGE)
        return 0 if verb else 2

    if verb == "run":
        rest = args[1:]
        seat = rest.pop(0) if rest and not rest[0].startswith("-") else "codex"
        return pi_run(seat, rest)

    if verb == "launch":
        rest = args[1:]
        from .cli import guard_tail
        rc = guard_tail("helm pi launch", rest,
                        valued=("--model", "--session-dir", "--session", "--print"),
                        usage=_USAGE)
        if rc is not None:
            return rc

        def opt(name, default=None):
            return rest[rest.index(name) + 1] if name in rest \
                   and rest.index(name) + 1 < len(rest) else default

        binary = pi_binary()
        if not binary:
            print("helm pi: `pi` not found on PATH", file=sys.stderr)
            return 1
        kwargs = {"binary": binary, "model": opt("--model"),
                  "session_dir": opt("--session-dir"),
                  "session": opt("--session"),
                  "prompt": opt("--print")}
        line = pi_launch_line(**kwargs)
        if line:
            print(line)
            return 0
        print("helm pi: launch line is empty — check pi is installed",
              file=sys.stderr)
        return 1

    if verb == "resume":
        rest = args[1:]
        from .cli import guard_tail
        rc = guard_tail("helm pi resume", rest,
                        flags=("--continue",),
                        valued=("--session-dir", "--session"),
                        usage=_USAGE)
        if rc is not None:
            return rc

        def opt(name, default=None):
            return rest[rest.index(name) + 1] if name in rest \
                   and rest.index(name) + 1 < len(rest) else default

        binary = pi_binary()
        if not binary:
            print("helm pi: `pi` not found on PATH", file=sys.stderr)
            return 1

        if "--continue" in rest:
            line = pi_launch_line(binary=binary, continue_recent=True,
                                  session_dir=opt("--session-dir"))
        elif opt("--session"):
            line = pi_launch_line(binary=binary, session=opt("--session"),
                                  session_dir=opt("--session-dir"))
        else:
            print("helm pi resume: pass --session <id> or --continue",
                  file=sys.stderr)
            return 2
        if line:
            print(line)
            return 0
        print("helm pi: launch line is empty — check pi is installed",
              file=sys.stderr)
        return 1

    if verb == "status":
        import shutil
        from . import harnesses
        binp = shutil.which("pi")
        print("pi binary:   %s" % (binp or "MISSING from PATH"))
        root = harnesses.pi_session_root()
        print("sessions:    %s%s" % (root, "" if os.path.isdir(root)
                                     else "  (absent)"))
        obs = harnesses.pi_observations()
        print("[helm pi] sees:   %d project(s) with pi sessions" % len(obs))
        for o in sorted(obs, key=lambda x: -x["last_seen"])[:5]:
            print("   %-46s %d session(s)" % (o["cwd"], o["sessions"]))
        ext = DEFAULT_DIR
        gen = sorted(f for f in (os.listdir(ext) if os.path.isdir(ext) else [])
                     if f.startswith("helm-"))
        print("[helm pi] shims:  %s" % (", ".join(gen) or "none generated"))
        return 0 if binp else 1

    if verb != "extension":
        print("helm pi: unknown verb '%s'" % verb, file=sys.stderr)
        print(_USAGE, file=sys.stderr)
        return 2

    rest = args[1:]
    from .cli import guard_tail
    # the WHOLE tail, not just the --flags: pre-filtering to dashed tokens
    # strips a valued flag's value, so `--seat codex` arrives as a bare
    # `--seat` and guard_tail correctly complains that it wants one. `pi
    # extension` takes no positionals, so nothing else can trip it.
    rc = guard_tail("helm pi extension", rest,
                    flags=("--apply",), valued=("--seat", "--out", "--model"),
                    usage=_USAGE)
    if rc is not None:
        return rc

    def opt(name, default=None):
        return rest[rest.index(name) + 1] if name in rest \
            and rest.index(name) + 1 < len(rest) else default

    seat = opt("--seat", "codex")
    path, src, err = write_extension(seat, out=opt("--out"),
                                     model=opt("--model"),
                                     apply="--apply" in rest)
    if err:
        print("helm pi: " + err, file=sys.stderr)
        return 1
    if "--apply" in rest:
        print("helm pi: wrote %s" % path)
        print("  export %s from the seat's proxy config before launching pi;"
              % KEY_ENV)
        print("  helm does not print it. Then: pi --provider %s"
              % provider_name(seat))
        return 0
    print(src)
    print("# not written — pass --apply to install at %s" % path,
          file=sys.stderr)
    return 0


# ---------------------------------------------------------------------------
# launch / resume recipes — the verbs this seam exists to make possible
# ---------------------------------------------------------------------------

# pi stamps PI_CODING_AGENT="true" at its own startup (cli.ts:13) —
# unconditionally, and before helm's launch line has even exec'd. helm does
# NOT prefix it here; pi's own config owns the marker.


def pi_binary():
    """The pi executable, or None. which(pi) — pi ships its own binary name."""
    import shutil
    return shutil.which("pi")


def _pi_api_key(seat, family=None):
    """The seat's proxy API key (the api-keys stanza from its 0600
    config.yaml), or None. ONE narrow read — no full-config load that could
    get logged. The key value is secret: callers must NEVER print, log, or
    return it through a surface that renders it."""
    from . import seat as seatmod
    if family is None:
        family, _err = seatmod._seat_family(seat)
    if not family:
        return None                # unresolvable seat — no config to read
    try:
        config_path = os.path.join(seatmod._proxy_home(family, seat),
                                   "config.yaml")
        # Scope to the api-keys stanza only: everything between
        # 'api-keys:' and the next non-indented line.
        in_keys = False
        with open(config_path) as f:
            for line in f:
                stripped = line.strip()
                if stripped == "api-keys:":
                    in_keys = True
                    continue
                if not in_keys:
                    continue
                # a non-indented line after api-keys: — end of stanza
                if stripped and not line.startswith((" ", "\t")):
                    break
                if stripped.startswith("- "):
                    return stripped[2:].strip().strip('"')
    except (OSError, ValueError):
        pass
    return None


def _proxy_descriptor(seat):
    """Canonical runtime + default Pi model for one helm proxy seat."""
    from . import seat as seatmod
    family, err = seatmod._seat_family(seat)
    if err:
        return None, err
    model = (seatmod.FAMILIES.get(family) or {}).get("model")
    if not model:
        return None, "family %s declares no model" % family
    return {"runtime": {"agent_harness": "pi", "family": family,
                        "backend": "proxy"},
            "seat": "pi-" + seat,
            "model": provider_name(seat) + "/" + model}, None


def _runtime_prefix(model):
    """Launch labels; clear axes the selected provider cannot prove."""
    env = ["env", "-u", "HELM_MODEL_FAMILY", "-u", "HELM_MODEL_BACKEND",
           "HELM_AGENT_HARNESS=pi"]
    provider = str(model or "").split("/", 1)[0]
    if provider.startswith("helm-") and len(provider) > len("helm-"):
        desc, err = _proxy_descriptor(provider[len("helm-"):])
        if not err:
            runtime = desc["runtime"]
            env.extend(("HELM_MODEL_FAMILY=" + runtime["family"],
                        "HELM_MODEL_BACKEND=" + runtime["backend"],
                        "HELM_CHAT_NAME=" + desc["seat"]))
    return env


def pi_launch_line(binary=None, model=None, session=None, resume=False,
                   continue_recent=False, session_dir=None, prompt=None):
    """The exact pi launch command, for helm to print. The launch line NEVER
    carries the proxy key — that is set ONLY in the child's environment by
    `pi_run()`, which execs pi directly.

    Flags mirror pi's CLI (packages/coding-agent/src/cli/args.ts):
      --model provider/id:thinking  model selection
      --session <uuid|path>         resume a specific session
      --resume                      interactive session picker
      --continue                    continue the most recent session
      --print, -p <prompt>          non-interactive: process prompt and exit
      --session-dir <path>          override the default session directory

    pi stamps PI_CODING_AGENT=true at its own startup (cli.ts:13) —
    helm does NOT prefix it; the env is pi's own launch-time contract.
    Returns the launch line as a string, or None when pi is not installed.
    """
    binary = binary or pi_binary()
    if not binary:
        return None
    cmd = [binary]
    if model:
        cmd.extend(["--model", model])
    if session_dir:
        cmd.extend(["--session-dir", session_dir])
    if session:
        cmd.extend(["--session", session])
    if resume:
        cmd.append("--resume")
    if continue_recent:
        cmd.append("--continue")
    if prompt:
        # --print is boolean (args.ts:140); prompt is a POSITIONAL argument.
        # Append the unquoted prompt VALUE — the final shlex.quote in the join
        # will quote it once, avoiding double-quoting.
        cmd.extend(["--print", prompt])
    return " ".join(shlex.quote(p) for p in _runtime_prefix(model) + cmd)


def pi_run(seat="codex", args=None):
    """Exec pi through one helm seat's proxy, with key + runtime labels in env.

    The selected model is pinned to that seat's generated provider: a key in the
    environment does not itself route pi through the proxy. The key remains a
    Python environ assignment, never a returned/printed string or argv value.
    """
    binary = pi_binary()
    if not binary:
        return 1
    desc, err = _proxy_descriptor(seat)
    if err:
        print("helm pi: " + err, file=sys.stderr)
        return 1
    args = list(args or [])
    selected = []
    for i, arg in enumerate(args):
        if arg == "--model":
            selected.append(args[i + 1] if i + 1 < len(args) else "")
        elif arg.startswith("--model="):
            selected.append(arg.split("=", 1)[1])
    if len(selected) > 1 or selected == [""]:
        print("helm pi run: pass at most one valued --model", file=sys.stderr)
        return 2
    provider = selected[0].split("/", 1)[0] if selected else ""
    expected = provider_name(seat)
    if provider and provider != expected:
        print("helm pi run: --model must use %s (got %s)"
              % (expected, provider), file=sys.stderr)
        return 2
    if not selected:
        args[:0] = ["--model", desc["model"]]
    key = _pi_api_key(seat, desc["runtime"]["family"])
    if not key:
        print("helm pi: no proxy key for %s — cannot authenticate" % seat,
              file=sys.stderr)
        return 1
    env = os.environ.copy()
    env["HELM_PI_PROXY_KEY"] = key
    env["HELM_AGENT_HARNESS"] = desc["runtime"]["agent_harness"]
    env["HELM_MODEL_FAMILY"] = desc["runtime"]["family"]
    env["HELM_MODEL_BACKEND"] = desc["runtime"]["backend"]
    env["HELM_CHAT_NAME"] = desc["seat"]
    from . import seats
    seats.write_roster(desc["seat"], cwd=os.getcwd(), runtime=desc["runtime"],
                       presence_beat=False)
    cmd = [binary] + args
    os.execvpe(binary, cmd, env)
